package com.myapp.model;
// Generated 27/04/2017 10:27:18 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Calendario generated by hbm2java
 */
public class Calendario  implements java.io.Serializable {


     private String idTt;
     private Sala sala;
     private Tt tt;
     private Date fecha;
     private Integer opcion;

    public Calendario() {
    }

    public Calendario(Sala sala, Tt tt, Date fecha, Integer opcion) {
       this.sala = sala;
       this.tt = tt;
       this.fecha = fecha;
       this.opcion = opcion;
    }

    public String getIdTt() {
        return this.idTt;
    }

    public void setIdTt(String idTt) {
        this.idTt = idTt;
    }
    public Sala getSala() {
        return this.sala;
    }

    public void setSala(Sala sala) {
        this.sala = sala;
    }
    public Tt getTt() {
        return this.tt;
    }

    public void setTt(Tt tt) {
        this.tt = tt;
    }
    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Integer getOpcion() {
        return this.opcion;
    }

    public void setOpcion(Integer opcion) {
        this.opcion = opcion;
    }




}
