package com.myapp.model;
// Generated 14/05/2017 03:16:46 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Calendario generated by hbm2java
 */
public class Calendario  implements java.io.Serializable {


     private Integer idCalendario;
     private Tt tt;
     private Date fecha;
     private Sala sala;
     private Integer opcion;

    public Calendario() {
    }

    public Calendario(Tt tt, Date fecha, Sala sala, Integer opcion) {
       this.tt = tt;
       this.fecha = fecha;
       this.sala = sala;
       this.opcion = opcion;
    }
   
    public Integer getIdCalendario() {
        return this.idCalendario;
    }
    
    public void setIdCalendario(Integer idCalendario) {
        this.idCalendario = idCalendario;
    }
    public Tt getTt() {
        return this.tt;
    }
    
    public void setTt(Tt tt) {
        this.tt = tt;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Sala getSala() {
        return this.sala;
    }
    
    public void setSala(Sala sala) {
        this.sala = sala;
    }
    public Integer getOpcion() {
        return this.opcion;
    }
    
    public void setOpcion(Integer opcion) {
        this.opcion = opcion;
    }




}


