package com.myapp.model;
// Generated 27/04/2017 10:27:18 AM by Hibernate Tools 4.3.1



/**
 * Horario generated by hbm2java
 */
public class Horario  implements java.io.Serializable {


     private Integer idHorario;
     private Profesor profesor;
     private String lun;
     private String mar;
     private String mie;
     private String jue;
     private String vie;

    public Horario() {
    }

	
    public Horario(Profesor profesor) {
        this.profesor = profesor;
    }
    public Horario(Profesor profesor, String lun, String mar, String mie, String jue, String vie) {
       this.profesor = profesor;
       this.lun = lun;
       this.mar = mar;
       this.mie = mie;
       this.jue = jue;
       this.vie = vie;
    }
   
    public Integer getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(Integer idHorario) {
        this.idHorario = idHorario;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public String getLun() {
        return this.lun;
    }
    
    public void setLun(String lun) {
        this.lun = lun;
    }
    public String getMar() {
        return this.mar;
    }
    
    public void setMar(String mar) {
        this.mar = mar;
    }
    public String getMie() {
        return this.mie;
    }
    
    public void setMie(String mie) {
        this.mie = mie;
    }
    public String getJue() {
        return this.jue;
    }
    
    public void setJue(String jue) {
        this.jue = jue;
    }
    public String getVie() {
        return this.vie;
    }
    
    public void setVie(String vie) {
        this.vie = vie;
    }




}


