package com.myapp.model;
// Generated 14/05/2017 03:16:46 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Nohabil generated by hbm2java
 */
public class Nohabil  implements java.io.Serializable {


     private Integer id;
     private Date fecha;

    public Nohabil() {
    }

    public Nohabil(Date fecha) {
       this.fecha = fecha;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
}


