package com.myapp.model;
// Generated 27/04/2017 10:27:18 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sala generated by hbm2java
 */
public class Sala  implements java.io.Serializable {


     private Integer idSala;
     private String nombre;
     private Set<Calendario> calendarios = new HashSet<Calendario>(0);

    public Sala() {
    }

	
    public Sala(String nombre) {
        this.nombre = nombre;
    }
    public Sala(String nombre, Set<Calendario> calendarios) {
       this.nombre = nombre;
       this.calendarios = calendarios;
    }
   
    public Integer getIdSala() {
        return this.idSala;
    }
    
    public void setIdSala(Integer idSala) {
        this.idSala = idSala;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Calendario> getCalendarios() {
        return this.calendarios;
    }
    
    public void setCalendarios(Set<Calendario> calendarios) {
        this.calendarios = calendarios;
    }




}


