package com.myapp.model;
// Generated 14/05/2017 03:16:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tt generated by hbm2java
 */
public class Tt  implements java.io.Serializable {


     private String idTt;
     private String nombre;
     private int nivel;
     private Set<Calendario> calendarios = new HashSet<>(0);
     private Set<Alumno> alumnos = new HashSet<>(0);

    public Tt() {
    }

	
    public Tt(String idTt, String nombre, int nivel) {
        this.idTt = idTt;
        this.nombre = nombre;
        this.nivel = nivel;
    }
    public Tt(String idTt, String nombre, int nivel, Set<Calendario> calendarios, Set<Alumno> alumnos) {
       this.idTt = idTt;
       this.nombre = nombre;
       this.nivel = nivel;
       this.calendarios = calendarios;
       this.alumnos = alumnos;
    }
   
    public String getIdTt() {
        return this.idTt;
    }
    
    public void setIdTt(String idTt) {
        this.idTt = idTt;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getNivel() {
        return this.nivel;
    }
    
    public void setNivel(int nivel) {
        this.nivel = nivel;
    }
    public Set<Calendario> getCalendarios() {
        return this.calendarios;
    }
    
    public void setCalendarios(Set<Calendario> calendarios) {
        this.calendarios = calendarios;
    }
    public Set<Alumno> getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set<Alumno> alumnos) {
        this.alumnos = alumnos;
    }




}


