package model;
// Generated 4/02/2017 08:19:46 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Calendario generated by hbm2java
 */
public class Calendario  implements java.io.Serializable {


     private String idTt;
     private Sala sala;
     private Tt tt;
     private Date fecha;

    public Calendario() {
    }

    public Calendario(Sala sala, Tt tt, Date fecha) {
       this.sala = sala;
       this.tt = tt;
       this.fecha = fecha;
    }
   
    public String getIdTt() {
        return this.idTt;
    }
    
    public void setIdTt(String idTt) {
        this.idTt = idTt;
    }
    public Sala getSala() {
        return this.sala;
    }
    
    public void setSala(Sala sala) {
        this.sala = sala;
    }
    public Tt getTt() {
        return this.tt;
    }
    
    public void setTt(Tt tt) {
        this.tt = tt;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


